Update apis
ciphertrace/apis pull request #18
Opened 2022-06-27 15:54 UTC by DanielSollis

This PR updates the traveler api.proto to it's current state on prod and fixes some spelling errors.

/assign @dwheeler 
/cc @bbengfort 
/cc @skymeyer

2022-06-28 17:11 UTC, skymeyer commented
/ok-to-test

2022-06-28 19:03 UTC, skymeyer requested changes

2022-06-28 21:55 UTC, bbengfort commented on traveler/sunrise/v1/api.proto
> +}
@dwheeler this is an internal service right? 

@DanielSollis I don't think we need this in the public repo either since this RPC is only between the Traveler node and an internal service.

2022-06-28 21:56 UTC, bbengfort commented on traveler/v1/api.proto
> +option go_package = "github.com/apis/traveler/v1;api";
This is also unnecessary for these protocol buffers since they do not target a specific programming language.

2022-07-18 17:57 UTC, skymeyer commented
/approve

2022-07-18 18:03 UTC, merged